//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organic_Launch
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class Farm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Farm()
        {
            this.AccountDetails = new HashSet<AccountDetail>();
            this.FarmProducts = new HashSet<FarmProduct>();
        }
    
        [DisplayName("Farm ID")]
        public int farmID { get; set; }
        [DisplayName("Farm Name")]
        public string farmName { get; set; }
        [DisplayName("Farm Profile")]
        public string farmProfile { get; set; }
        [DisplayName("City")]
        public string farmCity { get; set; }
        [DisplayName("Province")]
        public string farmProvince { get; set; }
        [DisplayName("Postal Code")]
        public string farmZip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountDetail> AccountDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FarmProduct> FarmProducts { get; set; }
    }
}
