//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organic_Launch
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.FarmProducts = new HashSet<FarmProduct>();
        }
    
        public int productID { get; set; }
        public string productName { get; set; }
        [DisplayName("Price In Kg")]
        public Nullable<decimal> priceInKg { get; set; }
        public string productCategory { get; set; }
        public string productDescription { get; set; }
        public Nullable<int> qty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FarmProduct> FarmProducts { get; set; }
    }
}
